import React, {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const format=(x,digits=1)=>Number(x).toLocaleString(undefined,{maximumFractionDigits:digits});
const label=x=>x==='ridge'?'Ridge regression':'Weekly baseline';
async function request(path,signal){const response=await fetch(path,{signal});if(!response.ok){let detail='Request failed';try{detail=(await response.json()).detail||detail}catch{}throw new Error(typeof detail==='string'?detail:'Please check the selected values.')}return response.json()}

function Chart({series}){
 const history=series.history.slice(-42),future=series.forecast,all=[...history,...future];
 const W=1000,H=290,P=40,max=Math.max(...all.map(d=>d.upper??d.units),1)*1.12;
 const x=i=>P+i*(W-2*P)/(all.length-1),y=v=>H-P-v*(H-2*P)/max;
 const points=(rows,start)=>rows.map((d,i)=>`${x(i+start)},${y(d.units)}`).join(' ');
 const band=future.map((d,i)=>`${x(history.length+i)},${y(d.upper)}`).concat([...future].reverse().map((d,i)=>`${x(all.length-1-i)},${y(d.lower)}`)).join(' ');
 return <div className="chart-wrap"><svg className="chart" viewBox={`0 0 ${W} ${H}`} role="img" aria-label={`Daily units for ${series.sku}: six weeks of history and ${future.length} forecast days. Forecasts are estimates.`}>
 {[0,1,2,3,4].map(t=><g key={t}><line x1={P} x2={W-P} y1={y(t*max/4)} y2={y(t*max/4)} stroke="#e4e8e1"/><text x={P-8} y={y(t*max/4)+4} textAnchor="end" className="axis">{Math.round(t*max/4)}</text></g>)}
 <rect x={x(history.length-1)} y="15" width={W-P-x(history.length-1)} height={H-P-15} fill="#f3f6f0"/>
 <polygon points={band} fill="#d8e6d8"/>
 <polyline points={points(history,0)} fill="none" stroke="#1c5143" strokeWidth="3" strokeLinejoin="round"/>
 <polyline points={`${x(history.length-1)},${y(history.at(-1).units)} ${points(future,history.length)}`} fill="none" stroke="#d06b38" strokeWidth="3" strokeDasharray="7 5"/>
 <line x1={x(history.length-1)} x2={x(history.length-1)} y1="10" y2={H-P} stroke="#8f9e92" strokeDasharray="4 5"/>
 <text x={x(history.length-1)+10} y="28" className="axis">FORECAST</text>
 {[0,Math.floor(history.length/2),history.length-1,all.length-1].map(i=><text key={i} x={x(i)} y={H-10} textAnchor="middle" className="axis">{all[i].date.slice(5)}</text>)}
 </svg><div className="legend"><span><i className="actual"/>Observed sales</span><span><i className="predicted"/>Forecast</span><span><i className="range"/>Exploratory range</span></div></div>
}

function App(){
 const [catalog,setCatalog]=useState(null),[sku,setSku]=useState(''),[horizon,setHorizon]=useState(14),[series,setSeries]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0),[lead,setLead]=useState(7),[stock,setStock]=useState(100),[scenario,setScenario]=useState(null),[scenarioError,setScenarioError]=useState('');
 useEffect(()=>{const c=new AbortController();setError('');setLoading(true);request('/api/catalog',c.signal).then(data=>{if(!data.products.length)throw new Error('No products are available.');setCatalog(data);setSku(current=>current||data.products[0].sku)}).catch(e=>{if(e.name!=='AbortError'){setError(e.message);setLoading(false)}});return()=>c.abort()},[retry]);
 useEffect(()=>{if(!sku)return;const c=new AbortController();setLoading(true);setError('');request(`/api/forecast/${encodeURIComponent(sku)}?horizon=${horizon}`,c.signal).then(setSeries).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[sku,horizon,retry]);
 useEffect(()=>{if(!sku)return;const c=new AbortController();setScenario(null);setScenarioError('');request(`/api/inventory/${encodeURIComponent(sku)}?lead_days=${lead}&on_hand=${stock}`,c.signal).then(setScenario).catch(e=>{if(e.name!=='AbortError')setScenarioError(e.message)});return()=>c.abort()},[sku,lead,stock,retry]);
 const total=series?.forecast.reduce((s,p)=>s+p.units,0)||0;
 const current=series?.holdout[series.selected_model];
 function download(){if(!series)return;const rows=['date,forecast_units,lower,upper',...series.forecast.map(p=>[p.date,p.units,p.lower,p.upper].join(','))];const url=URL.createObjectURL(new Blob([rows.join('\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=`forecast-${sku.replace(/[^\w-]/g,'_')}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <><header className="topbar"><a className="brand" href="/" aria-label="DemandLab home"><span className="brandmark">d</span>DemandLab<span className="brand-note">RETAIL INTELLIGENCE</span></a><a className="docs" href="/docs">API documentation ↗</a></header>
 <main><div className="intro"><div><p className="eyebrow">FORECASTING WORKSPACE</p><h1>A clearer view of<br/><em>what comes next.</em></h1><p className="lede">Explore demand, compare models, and make inventory decisions with the evidence in view.</p></div><aside className="dataset"><span className="status-dot"/> {catalog?.data_origin||'Loading dataset'}<small>Historical data · portfolio demonstration</small><p>No live store connection.<br/>Forecasts are estimates, not guarantees.</p></aside></div>
 <section className="controls" aria-label="Forecast controls"><label>Product<select value={sku} onChange={e=>setSku(e.target.value)} disabled={!catalog}>{catalog?.products.map(p=><option key={p.sku} value={p.sku}>{p.sku} · {p.description||p.sku}</option>)}</select></label><label>Forecast window<select value={horizon} onChange={e=>setHorizon(Number(e.target.value))}>{[7,14,28].map(n=><option key={n} value={n}>{n} days</option>)}</select></label><div className="control-spacer"/><button className="export" onClick={download} disabled={!series||loading}>Export forecast ↓</button></section>
 {error?<section role="alert" className="notice"><h2>We couldn’t load this forecast.</h2><p>{error}</p><button onClick={()=>setRetry(v=>v+1)}>Try again</button></section>:loading?<div className="loading" role="status">Preparing your forecast…</div>:series&&<>
 <section className="metrics" aria-label="Forecast summary"><article><span>Expected demand · {horizon} days</span><strong>{format(total,0)} <small>units</small></strong><p>Sum of daily forecast estimates</p></article><article><span>Selected model</span><strong className="model-name">{label(series.selected_model)}</strong><p>Selected using earlier validation windows</p></article><article><span>Holdout error · MAE</span><strong>{format(current.mae,2)} <small>units/day</small></strong><p>Final 28 days, excluded from selection</p></article></section>
 <section className="panel"><div className="panel-heading"><div><p className="eyebrow">DEMAND OUTLOOK</p><h2>History meets the horizon</h2></div><span className="pill">Observed through {series.history_end}</span></div><Chart series={series}/><p className="chart-note">{catalog.interval_note} Observed holdout coverage: {format(series.holdout_coverage*100,0)}%.</p><details><summary>View forecast values as a table</summary><div className="table-scroll"><table><thead><tr><th>Date</th><th>Forecast units</th><th>Lower estimate</th><th>Upper estimate</th></tr></thead><tbody>{series.forecast.map(p=><tr key={p.date}><td>{p.date}</td><td>{format(p.units)}</td><td>{format(p.lower)}</td><td>{format(p.upper)}</td></tr>)}</tbody></table></div></details></section>
 <div className="bottom-grid"><section className="panel"><p className="eyebrow">MODEL SCORECARD</p><h2>Does complexity earn its place?</h2><p className="muted">Both candidates face the same untouched 28-day holdout. Lower error is better.</p><div className="table-scroll"><table><thead><tr><th>Model</th><th>Validation MAE</th><th>Holdout MAE</th><th>WAPE</th></tr></thead><tbody>{Object.entries(series.holdout).map(([name,m])=><tr key={name}><td>{label(name)}{name===series.selected_model&&<span className="selected">Selected</span>}</td><td>{format(series.validation[name].mae,2)}</td><td>{format(m.mae,2)}</td><td>{m.wape===null?'Undefined':format(m.wape*100,1)+'%'}</td></tr>)}</tbody></table></div><p className="footnote">MAE: mean absolute error in units. WAPE: total absolute error divided by total observed units. Model choice uses validation, not this holdout.</p></section>
 <section className="panel inventory"><p className="eyebrow">WHAT-IF PLANNING</p><h2>Explore an inventory scenario</h2><div className="scenario-inputs"><label>Lead time · days<input type="number" min="1" max="28" value={lead} onChange={e=>setLead(Math.min(28,Math.max(1,Number(e.target.value))))}/></label><label>Units on hand<input type="number" min="0" max="1000000" value={stock} onChange={e=>setStock(Math.min(1000000,Math.max(0,Number(e.target.value))))}/></label></div>{scenarioError?<p role="alert">{scenarioError}</p>:<div className="order"><span>Illustrative order quantity</span><strong>{scenario?format(scenario.suggested_order,0):'…'} <small>units</small></strong></div>}<p className="footnote">Demand-only calculation. Excludes safety stock, open orders, costs and supplier constraints. It is not an optimized purchasing recommendation.</p></section></div>
 <section className="method"><span>01 <b>Prepare daily sales</b></span><span>02 <b>Validate chronologically</b></span><span>03 <b>Compare on holdout</b></span><span>04 <b>Refit and forecast</b></span></section></>}
 <footer><span>DemandLab · An open, reproducible forecasting project</span><a href="https://github.com/SJ-14-SJ/demand-forecasting-app">View source ↗</a></footer></main></>;
}
createRoot(document.getElementById('root')).render(<App/>);
